### ISSUE TITLE
CHromedriver Problem

### ISSUE THREAD

**Issue by Rawi1005** [sangeeta-dev/outlook-account-generator#27]
### Description

Having Problem about chromedriver

### Steps to Reproduce

1. install as normal
2. run the program

**Reproduces how often:**  100 percent

### Additional context
having a error about chrome driver not in path 

`
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\outlook-account-generator\main.py", line 5, in <module>
    Outlook.create_accounts(key="MYCAPKEEY",count=3)
  File "G:\outlook-account-generator\src\outlook\outlook.py", line 154, in create_accounts
    ctd = create_accounts(ls, parallel=parallel)
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\botasaurus\decorators.py", line 515, in wrapper_browser
    result = (Parallel(n_jobs=n, backend="threading")(delayed(run)(l) for l in used_data))
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
selenium.common.exceptions.WebDriverException: Message: 'chromedriver-121.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

`

**Comment by mostdoqe** [comment]
Same issue here, started happening today after it downloaded new chromedriver
